<a href="https://colab.research.google.com/github/leechungpa/Financial_Engineering_intro/blob/master/course/%EA%B8%88%EC%9C%B5%EA%B3%B5%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 딥러닝 (5/23)


In [0]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [0]:
my_model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, input_shape=[2],activation='relu'),
    tf.keras.layers.Dense(1)  #Dense 레이어의 경우 2번째 레이어 부터는 input_shape 필요 없음
]) 
my_model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 4         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [0]:
my_model.compile(
    loss = 'mse',
    optimizer = 'adam'
)
my_model.fit([[0,2]], [1],epochs=100,verbose=False) # vaerbose하면 결과를 간단히 보여줌

In [0]:
my_model.predict([[0.5,3]])

array([[-0.8344178]], dtype=float32)

In [0]:
my_model.get_weights()

[array([[ 0.04514015, -0.9103372 , -0.90085006],
        [ 0.9957013 , -0.72961307, -0.12324351]], dtype=float32),
 array([-0.0917602,  0.       ,  0.       ], dtype=float32),
 array([[-0.3188962 ],
        [ 1.0906461 ],
        [-0.29893494]], dtype=float32),
 array([0.09609382], dtype=float32)]

# 콜옵션

In [0]:
def call_option(S,u,d,r,K):
  prob = (r-d)/(u-d)
  value =1/r*(max(u*S-K,0)*prob +max(d*S-K,0)*(1-prob))
  return value

In [ ]:
for S in range(80,120,10) :
  for K in range(80,120,5) :
    print(S, K, call_option(S,1.1,0.9,1.05,K))
# 이런식으로 u d r 적어본다.
# 일부로 error를 넣을 수도 있다.

In [0]:
data =[]

for S in range(80,121,5) :
  data.append([S,call_option(S,1.1,0.9,1.05,100)])

data

[[80, 0.0],
 [85, 0.0],
 [90, 0.0],
 [95, 3.2142857142857237],
 [100, 7.142857142857152],
 [105, 11.07142857142858],
 [110, 15.000000000000007],
 [115, 19.761904761904766],
 [120, 24.761904761904756]]

In [0]:
import numpy as np
dt = np.array(data)
dt

array([[ 80.        ,   0.        ],
       [ 85.        ,   0.        ],
       [ 90.        ,   0.        ],
       [ 95.        ,   3.21428571],
       [100.        ,   7.14285714],
       [105.        ,  11.07142857],
       [110.        ,  15.        ],
       [115.        ,  19.76190476],
       [120.        ,  24.76190476]])

In [0]:
x = dt[:,0] # data 는 슬라이싱 불가능
y = dt[:,1]

In [0]:
co_model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_shape=[1],activation='relu'),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(1)
])
co_model.compile(loss='mse',optimizer='adam')

In [0]:
co_model.fit(x,y,epochs=10000,verbose=False)

In [0]:
co_model.predict([100])

array([[6.2942004]], dtype=float32)